# docker-compose.yml

app:
  image: ${yourname}/${yourapp}
  ports:
    - "80:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=${https://quiz.bantubeli.com}
    - MONGO_URL=mongodb://srv-captain--dbquiz:27017/meteor
    - METEOR_SETTINGS=${settings.json}

mongo:
  image: mongo:latest
  command:
    - --storageEngine=wiredTiger
  volumes:
    - ${/path/to/some/folder}:/data/db
